using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace InfHelper.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class InfSectionGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
		IncrementalValuesProvider<EnumDetails?> infSections = context.SyntaxProvider
			.ForAttributeWithMetadataName(
				"InfHelper.Models.Attributes.InfGeneratorAttribute",
				predicate: (_, _) => true,
				transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx)); // 👈 The original transform


		var pipeline = context.CompilationProvider.Combine(candidates.Collect());
        context.RegisterSourceOutput(pipeline, static (spc, pair) => Execute(pair.Left, pair.Right!, spc));
    }

    private static TypeDeclarationSyntax? FilterTypes(GeneratorSyntaxContext ctx)
    {
        var tds = (TypeDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(tds) as INamedTypeSymbol;
        if (symbol is null) return null;

        // Target any type that implements IInfSection<T> for itself (including via nested IInfTopLevelSection)
        bool implements = symbol.AllInterfaces.Any(i => i.Name == "IInfSection"
            && i.TypeArguments.Length == 1
            && SymbolEqualityComparer.Default.Equals(i.TypeArguments[0], symbol));

        return implements ? tds : null;
    }

    private static void Execute(Compilation compilation, ImmutableArray<TypeDeclarationSyntax> types, SourceProductionContext ctx)
    {
        if (types.IsDefaultOrEmpty) return;

        foreach (var t in types)
        {
            var model = compilation.GetSemanticModel(t.SyntaxTree);
            if (model.GetDeclaredSymbol(t) is not INamedTypeSymbol symbol) continue;

            // Require partial
            if (!t.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
            {
                ReportPartialDiagnostic(ctx, t, symbol);
                continue;
            }

            var source = Generate(symbol);
            ctx.AddSource($"{symbol.Name}.InfSection.g.cs", source);
        }
    }

    private static void ReportPartialDiagnostic(SourceProductionContext ctx, TypeDeclarationSyntax t, INamedTypeSymbol symbol)
    {
        var descriptor = new DiagnosticDescriptor(
            id: "INFGEN001",
            title: "Type must be partial",
            messageFormat: "Type '{0}' must be partial to support InfSection generation",
            category: "InfHelper.Generators",
            DiagnosticSeverity.Error,
            isEnabledByDefault: true);
        ctx.ReportDiagnostic(Diagnostic.Create(descriptor, t.Identifier.GetLocation(), symbol.Name));
    }

    private static string Generate(INamedTypeSymbol type)
    {
        var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";").AppendLine();
        }

        // Imports for parameter types
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using global::InfHelper.Models;");

        var kind = type.IsRecord ? "record" : "class";

        sb.Append("partial ").Append(kind).Append(' ').Append(type.Name).AppendLine()
          .AppendLine("{")
          // explicit interface implementation of Create
          .Append("    static ").Append(type.Name).Append(" IInfSection<").Append(type.Name).Append(">.Create(").AppendLine()
          .AppendLine("        string name,")
          .AppendLine("        InfData data,")
          .AppendLine("        IEnumerable<Entry> entries)")
          .AppendLine("    {")
          .Append("        return new ").Append(type.Name).AppendLine("(name, data, entries);")
          .AppendLine("    }")
          .AppendLine();

        if (!HasRequiredCtor(type))
        {
            sb.Append("    private ").Append(type.Name).AppendLine("(string name, InfData data, IEnumerable<Entry> entries) : base(entries)")
              .AppendLine("    {")
              .AppendLine("        // generated")
              .AppendLine("    }");
        }

        sb.AppendLine().AppendLine("}");
        return sb.ToString();
    }

    private static bool HasRequiredCtor(INamedTypeSymbol type)
    {
        foreach (var ctor in type.Constructors)
        {
            var ps = ctor.Parameters;
            if (ps.Length != 3) continue;
            if (ps[0].Type.SpecialType != SpecialType.System_String) continue;

            if (ps[1].Type is not INamedTypeSymbol p1 || p1.Name != "InfData") continue;

            if (ps[2].Type is not INamedTypeSymbol p2 || p2.Name != "IEnumerable") continue;
            if (p2.TypeArguments.Length != 1) continue;
            if (p2.TypeArguments[0] is not INamedTypeSymbol p2Arg || p2Arg.Name != "Entry") continue;
            return true;
        }
        return false;
    }
}
